// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: node/bandwidth.proto

package node

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BandwidthService_StartTest_FullMethodName           = "/node.BandwidthService/StartTest"
	BandwidthService_StreamUpload_FullMethodName        = "/node.BandwidthService/StreamUpload"
	BandwidthService_StreamDownload_FullMethodName      = "/node.BandwidthService/StreamDownload"
	BandwidthService_BidirectionalStream_FullMethodName = "/node.BandwidthService/BidirectionalStream"
	BandwidthService_GetTestStatus_FullMethodName       = "/node.BandwidthService/GetTestStatus"
	BandwidthService_CancelTest_FullMethodName          = "/node.BandwidthService/CancelTest"
	BandwidthService_GetTestResults_FullMethodName      = "/node.BandwidthService/GetTestResults"
)

// BandwidthServiceClient is the client API for BandwidthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BandwidthService handles bandwidth testing between nodes
type BandwidthServiceClient interface {
	// StartTest initiates a bandwidth test
	StartTest(ctx context.Context, in *StartTestRequest, opts ...grpc.CallOption) (*StartTestResponse, error)
	// StreamUpload streams data from client to server (upload test)
	StreamUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, StreamResult], error)
	// StreamDownload streams data from server to client (download test)
	StreamDownload(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	// BidirectionalStream for bidirectional bandwidth testing
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataChunk, DataChunk], error)
	// GetTestStatus returns current test status
	GetTestStatus(ctx context.Context, in *GetTestStatusRequest, opts ...grpc.CallOption) (*TestStatus, error)
	// CancelTest cancels a running test
	CancelTest(ctx context.Context, in *CancelTestRequest, opts ...grpc.CallOption) (*CancelTestResponse, error)
	// GetTestResults returns completed test results
	GetTestResults(ctx context.Context, in *GetTestResultsRequest, opts ...grpc.CallOption) (*TestResults, error)
}

type bandwidthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBandwidthServiceClient(cc grpc.ClientConnInterface) BandwidthServiceClient {
	return &bandwidthServiceClient{cc}
}

func (c *bandwidthServiceClient) StartTest(ctx context.Context, in *StartTestRequest, opts ...grpc.CallOption) (*StartTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTestResponse)
	err := c.cc.Invoke(ctx, BandwidthService_StartTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bandwidthServiceClient) StreamUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, StreamResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BandwidthService_ServiceDesc.Streams[0], BandwidthService_StreamUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, StreamResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BandwidthService_StreamUploadClient = grpc.ClientStreamingClient[DataChunk, StreamResult]

func (c *bandwidthServiceClient) StreamDownload(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BandwidthService_ServiceDesc.Streams[1], BandwidthService_StreamDownload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BandwidthService_StreamDownloadClient = grpc.ServerStreamingClient[DataChunk]

func (c *bandwidthServiceClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataChunk, DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BandwidthService_ServiceDesc.Streams[2], BandwidthService_BidirectionalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, DataChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BandwidthService_BidirectionalStreamClient = grpc.BidiStreamingClient[DataChunk, DataChunk]

func (c *bandwidthServiceClient) GetTestStatus(ctx context.Context, in *GetTestStatusRequest, opts ...grpc.CallOption) (*TestStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestStatus)
	err := c.cc.Invoke(ctx, BandwidthService_GetTestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bandwidthServiceClient) CancelTest(ctx context.Context, in *CancelTestRequest, opts ...grpc.CallOption) (*CancelTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTestResponse)
	err := c.cc.Invoke(ctx, BandwidthService_CancelTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bandwidthServiceClient) GetTestResults(ctx context.Context, in *GetTestResultsRequest, opts ...grpc.CallOption) (*TestResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResults)
	err := c.cc.Invoke(ctx, BandwidthService_GetTestResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BandwidthServiceServer is the server API for BandwidthService service.
// All implementations must embed UnimplementedBandwidthServiceServer
// for forward compatibility.
//
// BandwidthService handles bandwidth testing between nodes
type BandwidthServiceServer interface {
	// StartTest initiates a bandwidth test
	StartTest(context.Context, *StartTestRequest) (*StartTestResponse, error)
	// StreamUpload streams data from client to server (upload test)
	StreamUpload(grpc.ClientStreamingServer[DataChunk, StreamResult]) error
	// StreamDownload streams data from server to client (download test)
	StreamDownload(*DownloadRequest, grpc.ServerStreamingServer[DataChunk]) error
	// BidirectionalStream for bidirectional bandwidth testing
	BidirectionalStream(grpc.BidiStreamingServer[DataChunk, DataChunk]) error
	// GetTestStatus returns current test status
	GetTestStatus(context.Context, *GetTestStatusRequest) (*TestStatus, error)
	// CancelTest cancels a running test
	CancelTest(context.Context, *CancelTestRequest) (*CancelTestResponse, error)
	// GetTestResults returns completed test results
	GetTestResults(context.Context, *GetTestResultsRequest) (*TestResults, error)
	mustEmbedUnimplementedBandwidthServiceServer()
}

// UnimplementedBandwidthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBandwidthServiceServer struct{}

func (UnimplementedBandwidthServiceServer) StartTest(context.Context, *StartTestRequest) (*StartTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTest not implemented")
}
func (UnimplementedBandwidthServiceServer) StreamUpload(grpc.ClientStreamingServer[DataChunk, StreamResult]) error {
	return status.Error(codes.Unimplemented, "method StreamUpload not implemented")
}
func (UnimplementedBandwidthServiceServer) StreamDownload(*DownloadRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamDownload not implemented")
}
func (UnimplementedBandwidthServiceServer) BidirectionalStream(grpc.BidiStreamingServer[DataChunk, DataChunk]) error {
	return status.Error(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedBandwidthServiceServer) GetTestStatus(context.Context, *GetTestStatusRequest) (*TestStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTestStatus not implemented")
}
func (UnimplementedBandwidthServiceServer) CancelTest(context.Context, *CancelTestRequest) (*CancelTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTest not implemented")
}
func (UnimplementedBandwidthServiceServer) GetTestResults(context.Context, *GetTestResultsRequest) (*TestResults, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTestResults not implemented")
}
func (UnimplementedBandwidthServiceServer) mustEmbedUnimplementedBandwidthServiceServer() {}
func (UnimplementedBandwidthServiceServer) testEmbeddedByValue()                          {}

// UnsafeBandwidthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BandwidthServiceServer will
// result in compilation errors.
type UnsafeBandwidthServiceServer interface {
	mustEmbedUnimplementedBandwidthServiceServer()
}

func RegisterBandwidthServiceServer(s grpc.ServiceRegistrar, srv BandwidthServiceServer) {
	// If the following call panics, it indicates UnimplementedBandwidthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BandwidthService_ServiceDesc, srv)
}

func _BandwidthService_StartTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandwidthServiceServer).StartTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BandwidthService_StartTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandwidthServiceServer).StartTest(ctx, req.(*StartTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BandwidthService_StreamUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BandwidthServiceServer).StreamUpload(&grpc.GenericServerStream[DataChunk, StreamResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BandwidthService_StreamUploadServer = grpc.ClientStreamingServer[DataChunk, StreamResult]

func _BandwidthService_StreamDownload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BandwidthServiceServer).StreamDownload(m, &grpc.GenericServerStream[DownloadRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BandwidthService_StreamDownloadServer = grpc.ServerStreamingServer[DataChunk]

func _BandwidthService_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BandwidthServiceServer).BidirectionalStream(&grpc.GenericServerStream[DataChunk, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BandwidthService_BidirectionalStreamServer = grpc.BidiStreamingServer[DataChunk, DataChunk]

func _BandwidthService_GetTestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandwidthServiceServer).GetTestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BandwidthService_GetTestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandwidthServiceServer).GetTestStatus(ctx, req.(*GetTestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BandwidthService_CancelTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandwidthServiceServer).CancelTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BandwidthService_CancelTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandwidthServiceServer).CancelTest(ctx, req.(*CancelTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BandwidthService_GetTestResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandwidthServiceServer).GetTestResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BandwidthService_GetTestResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandwidthServiceServer).GetTestResults(ctx, req.(*GetTestResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BandwidthService_ServiceDesc is the grpc.ServiceDesc for BandwidthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BandwidthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.BandwidthService",
	HandlerType: (*BandwidthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTest",
			Handler:    _BandwidthService_StartTest_Handler,
		},
		{
			MethodName: "GetTestStatus",
			Handler:    _BandwidthService_GetTestStatus_Handler,
		},
		{
			MethodName: "CancelTest",
			Handler:    _BandwidthService_CancelTest_Handler,
		},
		{
			MethodName: "GetTestResults",
			Handler:    _BandwidthService_GetTestResults_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpload",
			Handler:       _BandwidthService_StreamUpload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamDownload",
			Handler:       _BandwidthService_StreamDownload_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidirectionalStream",
			Handler:       _BandwidthService_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node/bandwidth.proto",
}
