// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: node/bandwidth.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestType enum for test types
type TestType int32

const (
	TestType_TEST_TYPE_UNSPECIFIED   TestType = 0
	TestType_TEST_TYPE_UPLOAD        TestType = 1
	TestType_TEST_TYPE_DOWNLOAD      TestType = 2
	TestType_TEST_TYPE_BIDIRECTIONAL TestType = 3
)

// Enum value maps for TestType.
var (
	TestType_name = map[int32]string{
		0: "TEST_TYPE_UNSPECIFIED",
		1: "TEST_TYPE_UPLOAD",
		2: "TEST_TYPE_DOWNLOAD",
		3: "TEST_TYPE_BIDIRECTIONAL",
	}
	TestType_value = map[string]int32{
		"TEST_TYPE_UNSPECIFIED":   0,
		"TEST_TYPE_UPLOAD":        1,
		"TEST_TYPE_DOWNLOAD":      2,
		"TEST_TYPE_BIDIRECTIONAL": 3,
	}
)

func (x TestType) Enum() *TestType {
	p := new(TestType)
	*p = x
	return p
}

func (x TestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_bandwidth_proto_enumTypes[0].Descriptor()
}

func (TestType) Type() protoreflect.EnumType {
	return &file_node_bandwidth_proto_enumTypes[0]
}

func (x TestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestType.Descriptor instead.
func (TestType) EnumDescriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{0}
}

// TestMode enum for network path selection
// Controls how traffic is routed between nodes during bandwidth tests
type TestMode int32

const (
	TestMode_TEST_MODE_DIRECT  TestMode = 0 // Direct peer-to-peer connection (default)
	TestMode_TEST_MODE_LOCAL   TestMode = 1 // Force traffic through localhost/loopback (127.0.0.1)
	TestMode_TEST_MODE_GATEWAY TestMode = 2 // Route traffic through a specific gateway address
)

// Enum value maps for TestMode.
var (
	TestMode_name = map[int32]string{
		0: "TEST_MODE_DIRECT",
		1: "TEST_MODE_LOCAL",
		2: "TEST_MODE_GATEWAY",
	}
	TestMode_value = map[string]int32{
		"TEST_MODE_DIRECT":  0,
		"TEST_MODE_LOCAL":   1,
		"TEST_MODE_GATEWAY": 2,
	}
)

func (x TestMode) Enum() *TestMode {
	p := new(TestMode)
	*p = x
	return p
}

func (x TestMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestMode) Descriptor() protoreflect.EnumDescriptor {
	return file_node_bandwidth_proto_enumTypes[1].Descriptor()
}

func (TestMode) Type() protoreflect.EnumType {
	return &file_node_bandwidth_proto_enumTypes[1]
}

func (x TestMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestMode.Descriptor instead.
func (TestMode) EnumDescriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{1}
}

// TestState enum for test states
type TestState int32

const (
	TestState_TEST_STATE_UNSPECIFIED TestState = 0
	TestState_TEST_STATE_PENDING     TestState = 1
	TestState_TEST_STATE_RUNNING     TestState = 2
	TestState_TEST_STATE_COMPLETED   TestState = 3
	TestState_TEST_STATE_FAILED      TestState = 4
	TestState_TEST_STATE_CANCELLED   TestState = 5
)

// Enum value maps for TestState.
var (
	TestState_name = map[int32]string{
		0: "TEST_STATE_UNSPECIFIED",
		1: "TEST_STATE_PENDING",
		2: "TEST_STATE_RUNNING",
		3: "TEST_STATE_COMPLETED",
		4: "TEST_STATE_FAILED",
		5: "TEST_STATE_CANCELLED",
	}
	TestState_value = map[string]int32{
		"TEST_STATE_UNSPECIFIED": 0,
		"TEST_STATE_PENDING":     1,
		"TEST_STATE_RUNNING":     2,
		"TEST_STATE_COMPLETED":   3,
		"TEST_STATE_FAILED":      4,
		"TEST_STATE_CANCELLED":   5,
	}
)

func (x TestState) Enum() *TestState {
	p := new(TestState)
	*p = x
	return p
}

func (x TestState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestState) Descriptor() protoreflect.EnumDescriptor {
	return file_node_bandwidth_proto_enumTypes[2].Descriptor()
}

func (TestState) Type() protoreflect.EnumType {
	return &file_node_bandwidth_proto_enumTypes[2]
}

func (x TestState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestState.Descriptor instead.
func (TestState) EnumDescriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{2}
}

// StartTestRequest initiates a bandwidth test
type StartTestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TestId          string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	SourceNodeId    string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId    string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	TestType        TestType               `protobuf:"varint,4,opt,name=test_type,json=testType,proto3,enum=node.TestType" json:"test_type,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	ChunkSize       int32                  `protobuf:"varint,6,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`                   // bytes per chunk, default 64KB
	ParallelStreams int32                  `protobuf:"varint,7,opt,name=parallel_streams,json=parallelStreams,proto3" json:"parallel_streams,omitempty"` // number of parallel streams, default 1
	TestMode        TestMode               `protobuf:"varint,8,opt,name=test_mode,json=testMode,proto3,enum=node.TestMode" json:"test_mode,omitempty"`   // Network path mode (direct, local, gateway)
	GatewayAddress  string                 `protobuf:"bytes,9,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`     // Gateway IP:port when test_mode is GATEWAY
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartTestRequest) Reset() {
	*x = StartTestRequest{}
	mi := &file_node_bandwidth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestRequest) ProtoMessage() {}

func (x *StartTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestRequest.ProtoReflect.Descriptor instead.
func (*StartTestRequest) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{0}
}

func (x *StartTestRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *StartTestRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *StartTestRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *StartTestRequest) GetTestType() TestType {
	if x != nil {
		return x.TestType
	}
	return TestType_TEST_TYPE_UNSPECIFIED
}

func (x *StartTestRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StartTestRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *StartTestRequest) GetParallelStreams() int32 {
	if x != nil {
		return x.ParallelStreams
	}
	return 0
}

func (x *StartTestRequest) GetTestMode() TestMode {
	if x != nil {
		return x.TestMode
	}
	return TestMode_TEST_MODE_DIRECT
}

func (x *StartTestRequest) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

// StartTestResponse confirms test start
type StartTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TestId        string                 `protobuf:"bytes,2,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTestResponse) Reset() {
	*x = StartTestResponse{}
	mi := &file_node_bandwidth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestResponse) ProtoMessage() {}

func (x *StartTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestResponse.ProtoReflect.Descriptor instead.
func (*StartTestResponse) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{1}
}

func (x *StartTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartTestResponse) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *StartTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartTestResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// DataChunk is a chunk of data for streaming
type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // nanosecond timestamp for accurate timing
	IsFinal       bool                   `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_node_bandwidth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{2}
}

func (x *DataChunk) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *DataChunk) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataChunk) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *DataChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// StreamResult summarizes a completed stream
type StreamResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestId         string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	TotalBytes     int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	TotalChunks    int64                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	DurationMs     int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ThroughputMbps float64                `protobuf:"fixed64,5,opt,name=throughput_mbps,json=throughputMbps,proto3" json:"throughput_mbps,omitempty"`
	AvgLatencyUs   int64                  `protobuf:"varint,6,opt,name=avg_latency_us,json=avgLatencyUs,proto3" json:"avg_latency_us,omitempty"`
	MinLatencyUs   int64                  `protobuf:"varint,7,opt,name=min_latency_us,json=minLatencyUs,proto3" json:"min_latency_us,omitempty"`
	MaxLatencyUs   int64                  `protobuf:"varint,8,opt,name=max_latency_us,json=maxLatencyUs,proto3" json:"max_latency_us,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamResult) Reset() {
	*x = StreamResult{}
	mi := &file_node_bandwidth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResult) ProtoMessage() {}

func (x *StreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResult.ProtoReflect.Descriptor instead.
func (*StreamResult) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{3}
}

func (x *StreamResult) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *StreamResult) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StreamResult) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *StreamResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StreamResult) GetThroughputMbps() float64 {
	if x != nil {
		return x.ThroughputMbps
	}
	return 0
}

func (x *StreamResult) GetAvgLatencyUs() int64 {
	if x != nil {
		return x.AvgLatencyUs
	}
	return 0
}

func (x *StreamResult) GetMinLatencyUs() int64 {
	if x != nil {
		return x.MinLatencyUs
	}
	return 0
}

func (x *StreamResult) GetMaxLatencyUs() int64 {
	if x != nil {
		return x.MaxLatencyUs
	}
	return 0
}

// DownloadRequest initiates a download stream
type DownloadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TestId          string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ChunkSize       int32                  `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_node_bandwidth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *DownloadRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *DownloadRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// GetTestStatusRequest queries test status
type GetTestStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestStatusRequest) Reset() {
	*x = GetTestStatusRequest{}
	mi := &file_node_bandwidth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestStatusRequest) ProtoMessage() {}

func (x *GetTestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTestStatusRequest) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{5}
}

func (x *GetTestStatusRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

// TestStatus reports current test status
type TestStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TestId              string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	State               TestState              `protobuf:"varint,2,opt,name=state,proto3,enum=node.TestState" json:"state,omitempty"`
	ProgressPercent     float64                `protobuf:"fixed64,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	BytesSent           int64                  `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived       int64                  `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	CurrentUploadMbps   float64                `protobuf:"fixed64,6,opt,name=current_upload_mbps,json=currentUploadMbps,proto3" json:"current_upload_mbps,omitempty"`
	CurrentDownloadMbps float64                `protobuf:"fixed64,7,opt,name=current_download_mbps,json=currentDownloadMbps,proto3" json:"current_download_mbps,omitempty"`
	ElapsedMs           int64                  `protobuf:"varint,8,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	RemainingMs         int64                  `protobuf:"varint,9,opt,name=remaining_ms,json=remainingMs,proto3" json:"remaining_ms,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TestStatus) Reset() {
	*x = TestStatus{}
	mi := &file_node_bandwidth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStatus) ProtoMessage() {}

func (x *TestStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStatus.ProtoReflect.Descriptor instead.
func (*TestStatus) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{6}
}

func (x *TestStatus) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestStatus) GetState() TestState {
	if x != nil {
		return x.State
	}
	return TestState_TEST_STATE_UNSPECIFIED
}

func (x *TestStatus) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *TestStatus) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TestStatus) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *TestStatus) GetCurrentUploadMbps() float64 {
	if x != nil {
		return x.CurrentUploadMbps
	}
	return 0
}

func (x *TestStatus) GetCurrentDownloadMbps() float64 {
	if x != nil {
		return x.CurrentDownloadMbps
	}
	return 0
}

func (x *TestStatus) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *TestStatus) GetRemainingMs() int64 {
	if x != nil {
		return x.RemainingMs
	}
	return 0
}

func (x *TestStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// CancelTestRequest cancels a running test
type CancelTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTestRequest) Reset() {
	*x = CancelTestRequest{}
	mi := &file_node_bandwidth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTestRequest) ProtoMessage() {}

func (x *CancelTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTestRequest.ProtoReflect.Descriptor instead.
func (*CancelTestRequest) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTestRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *CancelTestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CancelTestResponse confirms cancellation
type CancelTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTestResponse) Reset() {
	*x = CancelTestResponse{}
	mi := &file_node_bandwidth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTestResponse) ProtoMessage() {}

func (x *CancelTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTestResponse.ProtoReflect.Descriptor instead.
func (*CancelTestResponse) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetTestResultsRequest queries test results
type GetTestResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestResultsRequest) Reset() {
	*x = GetTestResultsRequest{}
	mi := &file_node_bandwidth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestResultsRequest) ProtoMessage() {}

func (x *GetTestResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestResultsRequest.ProtoReflect.Descriptor instead.
func (*GetTestResultsRequest) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{9}
}

func (x *GetTestResultsRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

// TestResults contains complete test results
type TestResults struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TestId       string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	SourceNodeId string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	TestType     TestType               `protobuf:"varint,4,opt,name=test_type,json=testType,proto3,enum=node.TestType" json:"test_type,omitempty"`
	State        TestState              `protobuf:"varint,5,opt,name=state,proto3,enum=node.TestState" json:"state,omitempty"`
	StartedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	DurationMs   int64                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Upload metrics
	BytesSent       int64   `protobuf:"varint,9,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	UploadSpeedMbps float64 `protobuf:"fixed64,10,opt,name=upload_speed_mbps,json=uploadSpeedMbps,proto3" json:"upload_speed_mbps,omitempty"`
	// Download metrics
	BytesReceived     int64   `protobuf:"varint,11,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	DownloadSpeedMbps float64 `protobuf:"fixed64,12,opt,name=download_speed_mbps,json=downloadSpeedMbps,proto3" json:"download_speed_mbps,omitempty"`
	// Latency metrics
	AvgLatencyUs int64   `protobuf:"varint,13,opt,name=avg_latency_us,json=avgLatencyUs,proto3" json:"avg_latency_us,omitempty"`
	MinLatencyUs int64   `protobuf:"varint,14,opt,name=min_latency_us,json=minLatencyUs,proto3" json:"min_latency_us,omitempty"`
	MaxLatencyUs int64   `protobuf:"varint,15,opt,name=max_latency_us,json=maxLatencyUs,proto3" json:"max_latency_us,omitempty"`
	JitterUs     float64 `protobuf:"fixed64,16,opt,name=jitter_us,json=jitterUs,proto3" json:"jitter_us,omitempty"`
	// Packet metrics
	PacketsSent       int64   `protobuf:"varint,17,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsReceived   int64   `protobuf:"varint,18,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketLossPercent float64 `protobuf:"fixed64,19,opt,name=packet_loss_percent,json=packetLossPercent,proto3" json:"packet_loss_percent,omitempty"`
	ErrorMessage      string  `protobuf:"bytes,20,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Network path info
	TestMode            TestMode `protobuf:"varint,21,opt,name=test_mode,json=testMode,proto3,enum=node.TestMode" json:"test_mode,omitempty"`
	GatewayAddress      string   `protobuf:"bytes,22,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	ActualTargetAddress string   `protobuf:"bytes,23,opt,name=actual_target_address,json=actualTargetAddress,proto3" json:"actual_target_address,omitempty"` // The actual IP:port used for the test
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TestResults) Reset() {
	*x = TestResults{}
	mi := &file_node_bandwidth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResults) ProtoMessage() {}

func (x *TestResults) ProtoReflect() protoreflect.Message {
	mi := &file_node_bandwidth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResults.ProtoReflect.Descriptor instead.
func (*TestResults) Descriptor() ([]byte, []int) {
	return file_node_bandwidth_proto_rawDescGZIP(), []int{10}
}

func (x *TestResults) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestResults) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *TestResults) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *TestResults) GetTestType() TestType {
	if x != nil {
		return x.TestType
	}
	return TestType_TEST_TYPE_UNSPECIFIED
}

func (x *TestResults) GetState() TestState {
	if x != nil {
		return x.State
	}
	return TestState_TEST_STATE_UNSPECIFIED
}

func (x *TestResults) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TestResults) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *TestResults) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TestResults) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TestResults) GetUploadSpeedMbps() float64 {
	if x != nil {
		return x.UploadSpeedMbps
	}
	return 0
}

func (x *TestResults) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *TestResults) GetDownloadSpeedMbps() float64 {
	if x != nil {
		return x.DownloadSpeedMbps
	}
	return 0
}

func (x *TestResults) GetAvgLatencyUs() int64 {
	if x != nil {
		return x.AvgLatencyUs
	}
	return 0
}

func (x *TestResults) GetMinLatencyUs() int64 {
	if x != nil {
		return x.MinLatencyUs
	}
	return 0
}

func (x *TestResults) GetMaxLatencyUs() int64 {
	if x != nil {
		return x.MaxLatencyUs
	}
	return 0
}

func (x *TestResults) GetJitterUs() float64 {
	if x != nil {
		return x.JitterUs
	}
	return 0
}

func (x *TestResults) GetPacketsSent() int64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *TestResults) GetPacketsReceived() int64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *TestResults) GetPacketLossPercent() float64 {
	if x != nil {
		return x.PacketLossPercent
	}
	return 0
}

func (x *TestResults) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TestResults) GetTestMode() TestMode {
	if x != nil {
		return x.TestMode
	}
	return TestMode_TEST_MODE_DIRECT
}

func (x *TestResults) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

func (x *TestResults) GetActualTargetAddress() string {
	if x != nil {
		return x.ActualTargetAddress
	}
	return ""
}

var File_node_bandwidth_proto protoreflect.FileDescriptor

const file_node_bandwidth_proto_rawDesc = "" +
	"\n" +
	"\x14node/bandwidth.proto\x12\x04node\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x02\n" +
	"\x10StartTestRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12+\n" +
	"\ttest_type\x18\x04 \x01(\x0e2\x0e.node.TestTypeR\btestType\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x06 \x01(\x05R\tchunkSize\x12)\n" +
	"\x10parallel_streams\x18\a \x01(\x05R\x0fparallelStreams\x12+\n" +
	"\ttest_mode\x18\b \x01(\x0e2\x0e.node.TestModeR\btestMode\x12'\n" +
	"\x0fgateway_address\x18\t \x01(\tR\x0egatewayAddress\"\x9b\x01\n" +
	"\x11StartTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atest_id\x18\x02 \x01(\tR\x06testId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x92\x01\n" +
	"\tDataChunk\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal\"\xa7\x02\n" +
	"\fStreamResult\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x03R\vtotalChunks\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12'\n" +
	"\x0fthroughput_mbps\x18\x05 \x01(\x01R\x0ethroughputMbps\x12$\n" +
	"\x0eavg_latency_us\x18\x06 \x01(\x03R\favgLatencyUs\x12$\n" +
	"\x0emin_latency_us\x18\a \x01(\x03R\fminLatencyUs\x12$\n" +
	"\x0emax_latency_us\x18\b \x01(\x03R\fmaxLatencyUs\"t\n" +
	"\x0fDownloadRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x05R\tchunkSize\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\"/\n" +
	"\x14GetTestStatusRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"\x88\x03\n" +
	"\n" +
	"TestStatus\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12%\n" +
	"\x05state\x18\x02 \x01(\x0e2\x0f.node.TestStateR\x05state\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x01R\x0fprogressPercent\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x03R\rbytesReceived\x12.\n" +
	"\x13current_upload_mbps\x18\x06 \x01(\x01R\x11currentUploadMbps\x122\n" +
	"\x15current_download_mbps\x18\a \x01(\x01R\x13currentDownloadMbps\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\b \x01(\x03R\telapsedMs\x12!\n" +
	"\fremaining_ms\x18\t \x01(\x03R\vremainingMs\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\"D\n" +
	"\x11CancelTestRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"H\n" +
	"\x12CancelTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x15GetTestResultsRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\"\xb7\a\n" +
	"\vTestResults\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12+\n" +
	"\ttest_type\x18\x04 \x01(\x0e2\x0e.node.TestTypeR\btestType\x12%\n" +
	"\x05state\x18\x05 \x01(\x0e2\x0f.node.TestStateR\x05state\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\t \x01(\x03R\tbytesSent\x12*\n" +
	"\x11upload_speed_mbps\x18\n" +
	" \x01(\x01R\x0fuploadSpeedMbps\x12%\n" +
	"\x0ebytes_received\x18\v \x01(\x03R\rbytesReceived\x12.\n" +
	"\x13download_speed_mbps\x18\f \x01(\x01R\x11downloadSpeedMbps\x12$\n" +
	"\x0eavg_latency_us\x18\r \x01(\x03R\favgLatencyUs\x12$\n" +
	"\x0emin_latency_us\x18\x0e \x01(\x03R\fminLatencyUs\x12$\n" +
	"\x0emax_latency_us\x18\x0f \x01(\x03R\fmaxLatencyUs\x12\x1b\n" +
	"\tjitter_us\x18\x10 \x01(\x01R\bjitterUs\x12!\n" +
	"\fpackets_sent\x18\x11 \x01(\x03R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\x12 \x01(\x03R\x0fpacketsReceived\x12.\n" +
	"\x13packet_loss_percent\x18\x13 \x01(\x01R\x11packetLossPercent\x12#\n" +
	"\rerror_message\x18\x14 \x01(\tR\ferrorMessage\x12+\n" +
	"\ttest_mode\x18\x15 \x01(\x0e2\x0e.node.TestModeR\btestMode\x12'\n" +
	"\x0fgateway_address\x18\x16 \x01(\tR\x0egatewayAddress\x122\n" +
	"\x15actual_target_address\x18\x17 \x01(\tR\x13actualTargetAddress*p\n" +
	"\bTestType\x12\x19\n" +
	"\x15TEST_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TEST_TYPE_UPLOAD\x10\x01\x12\x16\n" +
	"\x12TEST_TYPE_DOWNLOAD\x10\x02\x12\x1b\n" +
	"\x17TEST_TYPE_BIDIRECTIONAL\x10\x03*L\n" +
	"\bTestMode\x12\x14\n" +
	"\x10TEST_MODE_DIRECT\x10\x00\x12\x13\n" +
	"\x0fTEST_MODE_LOCAL\x10\x01\x12\x15\n" +
	"\x11TEST_MODE_GATEWAY\x10\x02*\xa2\x01\n" +
	"\tTestState\x12\x1a\n" +
	"\x16TEST_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TEST_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12TEST_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14TEST_STATE_COMPLETED\x10\x03\x12\x15\n" +
	"\x11TEST_STATE_FAILED\x10\x04\x12\x18\n" +
	"\x14TEST_STATE_CANCELLED\x10\x052\xc2\x03\n" +
	"\x10BandwidthService\x12<\n" +
	"\tStartTest\x12\x16.node.StartTestRequest\x1a\x17.node.StartTestResponse\x125\n" +
	"\fStreamUpload\x12\x0f.node.DataChunk\x1a\x12.node.StreamResult(\x01\x12:\n" +
	"\x0eStreamDownload\x12\x15.node.DownloadRequest\x1a\x0f.node.DataChunk0\x01\x12;\n" +
	"\x13BidirectionalStream\x12\x0f.node.DataChunk\x1a\x0f.node.DataChunk(\x010\x01\x12=\n" +
	"\rGetTestStatus\x12\x1a.node.GetTestStatusRequest\x1a\x10.node.TestStatus\x12?\n" +
	"\n" +
	"CancelTest\x12\x17.node.CancelTestRequest\x1a\x18.node.CancelTestResponse\x12@\n" +
	"\x0eGetTestResults\x12\x1b.node.GetTestResultsRequest\x1a\x11.node.TestResultsB&Z$github.com/networkmonitor/proto/nodeb\x06proto3"

var (
	file_node_bandwidth_proto_rawDescOnce sync.Once
	file_node_bandwidth_proto_rawDescData []byte
)

func file_node_bandwidth_proto_rawDescGZIP() []byte {
	file_node_bandwidth_proto_rawDescOnce.Do(func() {
		file_node_bandwidth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_bandwidth_proto_rawDesc), len(file_node_bandwidth_proto_rawDesc)))
	})
	return file_node_bandwidth_proto_rawDescData
}

var file_node_bandwidth_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_node_bandwidth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_node_bandwidth_proto_goTypes = []any{
	(TestType)(0),                 // 0: node.TestType
	(TestMode)(0),                 // 1: node.TestMode
	(TestState)(0),                // 2: node.TestState
	(*StartTestRequest)(nil),      // 3: node.StartTestRequest
	(*StartTestResponse)(nil),     // 4: node.StartTestResponse
	(*DataChunk)(nil),             // 5: node.DataChunk
	(*StreamResult)(nil),          // 6: node.StreamResult
	(*DownloadRequest)(nil),       // 7: node.DownloadRequest
	(*GetTestStatusRequest)(nil),  // 8: node.GetTestStatusRequest
	(*TestStatus)(nil),            // 9: node.TestStatus
	(*CancelTestRequest)(nil),     // 10: node.CancelTestRequest
	(*CancelTestResponse)(nil),    // 11: node.CancelTestResponse
	(*GetTestResultsRequest)(nil), // 12: node.GetTestResultsRequest
	(*TestResults)(nil),           // 13: node.TestResults
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_node_bandwidth_proto_depIdxs = []int32{
	0,  // 0: node.StartTestRequest.test_type:type_name -> node.TestType
	1,  // 1: node.StartTestRequest.test_mode:type_name -> node.TestMode
	14, // 2: node.StartTestResponse.started_at:type_name -> google.protobuf.Timestamp
	2,  // 3: node.TestStatus.state:type_name -> node.TestState
	0,  // 4: node.TestResults.test_type:type_name -> node.TestType
	2,  // 5: node.TestResults.state:type_name -> node.TestState
	14, // 6: node.TestResults.started_at:type_name -> google.protobuf.Timestamp
	14, // 7: node.TestResults.ended_at:type_name -> google.protobuf.Timestamp
	1,  // 8: node.TestResults.test_mode:type_name -> node.TestMode
	3,  // 9: node.BandwidthService.StartTest:input_type -> node.StartTestRequest
	5,  // 10: node.BandwidthService.StreamUpload:input_type -> node.DataChunk
	7,  // 11: node.BandwidthService.StreamDownload:input_type -> node.DownloadRequest
	5,  // 12: node.BandwidthService.BidirectionalStream:input_type -> node.DataChunk
	8,  // 13: node.BandwidthService.GetTestStatus:input_type -> node.GetTestStatusRequest
	10, // 14: node.BandwidthService.CancelTest:input_type -> node.CancelTestRequest
	12, // 15: node.BandwidthService.GetTestResults:input_type -> node.GetTestResultsRequest
	4,  // 16: node.BandwidthService.StartTest:output_type -> node.StartTestResponse
	6,  // 17: node.BandwidthService.StreamUpload:output_type -> node.StreamResult
	5,  // 18: node.BandwidthService.StreamDownload:output_type -> node.DataChunk
	5,  // 19: node.BandwidthService.BidirectionalStream:output_type -> node.DataChunk
	9,  // 20: node.BandwidthService.GetTestStatus:output_type -> node.TestStatus
	11, // 21: node.BandwidthService.CancelTest:output_type -> node.CancelTestResponse
	13, // 22: node.BandwidthService.GetTestResults:output_type -> node.TestResults
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_node_bandwidth_proto_init() }
func file_node_bandwidth_proto_init() {
	if File_node_bandwidth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_bandwidth_proto_rawDesc), len(file_node_bandwidth_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_bandwidth_proto_goTypes,
		DependencyIndexes: file_node_bandwidth_proto_depIdxs,
		EnumInfos:         file_node_bandwidth_proto_enumTypes,
		MessageInfos:      file_node_bandwidth_proto_msgTypes,
	}.Build()
	File_node_bandwidth_proto = out.File
	file_node_bandwidth_proto_goTypes = nil
	file_node_bandwidth_proto_depIdxs = nil
}
